### ISSUE TITLE
docs-deploying-cf/openstack/cf-stub.html.md.erb missing documentation

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry/docs-deploying-cf#142]
Relevant page: https://docs.cloudfoundry.org/deploying/openstack/cf-stub.html

The provided manifest:

```
    scim:
      users:
      - name: admin
        password: ADMIN_PASSWORD
        groups:
        - scim.write
        - scim.read
        - openid
        - cloud_controller.admin
        - doppler.firehose
    sslCertificate: UAA_SERVER_CERT
    sslPrivateKey: UAA_SERVER_KEY
```

Neither `UAA_SERVER_CERT` nor `UAA_SERVER_KEY` is documented.

**Comment by jadekler** [comment]
Found another:

```
  databases:
    roles:
    - name: ccadmin
      password: some-ccdb-password
    - name: uaaadmin
      password: some-uaadb-password
    - name: diego
      password: DIEGODB_PASSWORD
```

DIEGODB_PASSWORD is undocumented.
